FROM node:20-alpine AS builder

RUN npm install -g pnpm

WORKDIR /app

COPY package.json pnpm-lock.yaml ./
RUN pnpm install --frozen-lockfile
    
COPY . .
RUN pnpm build
    
FROM node:20-alpine
    
RUN npm install -g pnpm
    
WORKDIR /app
    
COPY --from=builder /app/dist ./dist
COPY package.json ./
RUN pnpm install --prod --ignore-scripts
    
EXPOSE 4000
CMD ["node", "dist/src/main.js"] 