apiVersion: v2
name: kite
description: A Helm chart for Kite Kubernetes Dashboard
type: application
version: 0.1.0
appVersion: "0.8.1"
dependencies:
  - name: kite
    version: "0.8.1"
    repository: "https://kite-org.github.io/kite/"